/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brenda.libro.gui;

/**
 *
 * @author Ivan
 */
public class CuestionarioC12 extends javax.swing.JPanel {

    /**
     * Creates new form CuestionarioC2
     */
    public CuestionarioC12() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        buttonGroup21 = new javax.swing.ButtonGroup();
        buttonGroup22 = new javax.swing.ButtonGroup();
        buttonGroup23 = new javax.swing.ButtonGroup();
        buttonGroup24 = new javax.swing.ButtonGroup();
        buttonGroup25 = new javax.swing.ButtonGroup();
        buttonGroup26 = new javax.swing.ButtonGroup();
        buttonGroup27 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        btn_p1_SI = new javax.swing.JRadioButton();
        btn_p1_No = new javax.swing.JRadioButton();
        btn_p2_SI = new javax.swing.JRadioButton();
        btn_p2_No = new javax.swing.JRadioButton();
        btn_p3_SI = new javax.swing.JRadioButton();
        btn_p3_No = new javax.swing.JRadioButton();
        btn_p4_SI = new javax.swing.JRadioButton();
        btn_p4_No = new javax.swing.JRadioButton();
        btn_p5_SI = new javax.swing.JRadioButton();
        btn_p5_No = new javax.swing.JRadioButton();
        btn_p6_SI = new javax.swing.JRadioButton();
        btn_p6_No = new javax.swing.JRadioButton();
        btn_p7_SI = new javax.swing.JRadioButton();
        btn_p7_No = new javax.swing.JRadioButton();
        btn_p8_SI = new javax.swing.JRadioButton();
        btn_p8_no = new javax.swing.JRadioButton();
        btn_p9_SI = new javax.swing.JRadioButton();
        btn_p9_no = new javax.swing.JRadioButton();
        btn_p10_SI = new javax.swing.JRadioButton();
        btn_p10_no = new javax.swing.JRadioButton();
        btn_p11_SI = new javax.swing.JRadioButton();
        btn_p11_no = new javax.swing.JRadioButton();
        btn_p12_SI = new javax.swing.JRadioButton();
        btn_p12_no = new javax.swing.JRadioButton();
        btn_p13_SI = new javax.swing.JRadioButton();
        btn_p13_no = new javax.swing.JRadioButton();
        btn_p14_SI = new javax.swing.JRadioButton();
        btn_p14_no = new javax.swing.JRadioButton();
        btn_p15_SI = new javax.swing.JRadioButton();
        btn_p15_no = new javax.swing.JRadioButton();
        btn_p16_SI = new javax.swing.JRadioButton();
        btn_p16_no = new javax.swing.JRadioButton();
        btn_p17_SI = new javax.swing.JRadioButton();
        btn_p17_no = new javax.swing.JRadioButton();
        btn_p18_SI = new javax.swing.JRadioButton();
        btn_p18_no = new javax.swing.JRadioButton();
        btn_p19_SI = new javax.swing.JRadioButton();
        btn_p19_no = new javax.swing.JRadioButton();
        btn_p20_SI = new javax.swing.JRadioButton();
        btn_p20_no = new javax.swing.JRadioButton();
        btn_p21_SI = new javax.swing.JRadioButton();
        btn_p21_no = new javax.swing.JRadioButton();
        btn_p22_SI = new javax.swing.JRadioButton();
        btn_p22_no = new javax.swing.JRadioButton();
        btn_p23_SI = new javax.swing.JRadioButton();
        btn_p23_no = new javax.swing.JRadioButton();
        btn_p24_SI = new javax.swing.JRadioButton();
        btn_p24_no = new javax.swing.JRadioButton();
        btn_p25_SI = new javax.swing.JRadioButton();
        btn_p25_no = new javax.swing.JRadioButton();
        btn_p26_SI = new javax.swing.JRadioButton();
        btn_p26_no = new javax.swing.JRadioButton();
        btn_p27_SI = new javax.swing.JRadioButton();
        btn_p27_no = new javax.swing.JRadioButton();
        btn_continuar = new javax.swing.JButton();

        jRadioButton7.setText("jRadioButton1");

        jRadioButton8.setText("jRadioButton2");

        jRadioButton17.setText("jRadioButton1");

        jRadioButton18.setText("jRadioButton2");

        buttonGroup1.add(btn_p1_SI);
        buttonGroup1.add(btn_p1_No);

        buttonGroup2.add(btn_p2_SI);
        buttonGroup2.add(btn_p2_No);

        buttonGroup3.add(btn_p3_SI);
        buttonGroup3.add(btn_p3_No);

        buttonGroup4.add(btn_p4_SI);
        buttonGroup4.add(btn_p4_No);

        buttonGroup5.add(btn_p5_SI);
        buttonGroup5.add(btn_p5_No);

        buttonGroup6.add(btn_p6_SI);
        buttonGroup6.add(btn_p6_No);

        buttonGroup7.add(btn_p7_SI);
        buttonGroup7.add(btn_p7_No);

        buttonGroup8.add(btn_p8_SI);
        buttonGroup8.add(btn_p8_no);

        buttonGroup9.add(btn_p9_SI);
        buttonGroup9.add(btn_p9_no);

        buttonGroup10.add(btn_p10_SI);
        buttonGroup10.add(btn_p10_no);

        buttonGroup11.add(btn_p11_SI);
        buttonGroup11.add(btn_p11_no);

        buttonGroup12.add(btn_p12_SI);
        buttonGroup12.add(btn_p12_no);

        buttonGroup13.add(btn_p13_SI);
        buttonGroup13.add(btn_p13_no);

        buttonGroup14.add(btn_p14_SI);
        buttonGroup14.add(btn_p14_no);

        buttonGroup15.add(btn_p15_SI);
        buttonGroup15.add(btn_p15_no);

        buttonGroup16.add(btn_p16_SI);
        buttonGroup16.add(btn_p16_no);

        buttonGroup17.add(btn_p17_SI);
        buttonGroup17.add(btn_p17_no);

        buttonGroup18.add(btn_p18_SI);
        buttonGroup18.add(btn_p18_no);

        buttonGroup19.add(btn_p19_SI);
        buttonGroup19.add(btn_p19_no);

        buttonGroup20.add(btn_p20_SI);
        buttonGroup20.add(btn_p20_no);

        buttonGroup21.add(btn_p21_SI);
        buttonGroup21.add(btn_p21_no);

        buttonGroup22.add(btn_p22_SI);
        buttonGroup22.add(btn_p22_no);

        buttonGroup23.add(btn_p23_SI);
        buttonGroup23.add(btn_p23_no);

        buttonGroup24.add(btn_p24_SI);
        buttonGroup24.add(btn_p24_no);

        buttonGroup25.add(btn_p25_SI);
        buttonGroup25.add(btn_p25_no);

        buttonGroup26.add(btn_p26_SI);
        buttonGroup26.add(btn_p26_no);

        buttonGroup27.add(btn_p27_SI);
        buttonGroup27.add(btn_p27_no);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 128));
        jLabel1.setText("Exploración: fondo de ojo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 183, 133));
        jLabel2.setText("Técnica: Oftalmoscopía");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 128));
        jLabel3.setText("SI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 128));
        jLabel4.setText("NO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 128));
        jLabel5.setText("Examina el ojo derecho del paciente con tu ojo derecho; y su ojo izquierdo con tu ojo izquierdo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 128));
        jLabel6.setText("Coloca el disco de lentes del oftalmoscopio en cero");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 128));
        jLabel7.setText("De primera instancia utiliza la luz blanca y circular");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 128));
        jLabel8.setText("Toma el oftalmoscopio con la mano derecha en posición vertical frente a tu ojo derecho");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 128));
        jLabel9.setText("y con el rayo luminoso dirigido al paciente");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 128));
        jLabel10.setText("Coloca el dedo índice en el disco de selección de lentes, para cambiar lentes en caso de ser necesario");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 128));
        jLabel11.setText("Indica a tu paciente que vea directamente hacia adelante hacia un punto fijo designado");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 128));
        jLabel12.setText("Frente al paciente, acercate a 15 cm. aproximadamente y a 25 grados a la derecha de el. Es importante cuidar");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 128));
        jLabel13.setText("que no obstruyas el campo visual del paciente para evitar movimientos oculares que dificulten la exploración");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 128));
        jLabel14.setText("Dirige el haz luminoso a la pupila y observa un \"reflejo rojo\" al ver a través de la abertura del oftalmoscopo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 128));
        jLabel15.setText("En el caso que no puedas observar a causa del reflejo de la luz, utiliza el haz luminoso las pequeño");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 128));
        jLabel16.setText(" del oftalmoscopio o bien dirige la fuente luminosa por la orilla de la pupila disminuyendo el ángulo de entrada");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 183, 133));
        jLabel17.setText("Tecnica: Oftalmoscopía");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 128));
        jLabel18.setText("SI");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 128));
        jLabel19.setText("NO");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 128));
        jLabel20.setText("Manteniendo la vista en el reflejo rojo acercate a una distancia de 3 a  5 cm. del ojo derecho de tu paciente");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 128));
        jLabel21.setText("Si no observas con claridad elfondo del ojo, rota el disco de lentes hasta enfocarlo. Localiza los vasos sanguíneos");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 128));
        jLabel22.setText("e identificalos como arteria o vena y estudia las características de cada uno de ellos siuirndo su trayecto:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 128));
        jLabel23.setText("* Recuerda que, la arteria rectilinea, con coloración rojo brillante y con mayor luminosidad en su trayecto y");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 128));
        jLabel24.setText("* Que las venas son más gruesas con coloración rojo oscuro, con trayecto sinuoso y sonmenos luminosas");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 128));
        jLabel25.setText("* Relación arteria/vena de 3:5 o de 1:3");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 128));
        jLabel26.setText("Siguiendo un vaso dirigete en sentido contrario a las ramificaciones o hacia donde se engrüesa; esto te llevará");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 128));
        jLabel27.setText("la mirada hacia la papila óptica o disco óptico que se encuentra hacia el borde nasal");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 128));
        jLabel28.setText("Para el examen de la mácula dirige la luz y la mirada hacia el lado temporal");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 128));
        jLabel29.setText("Para el examen de la retina paracentral, debes dirigir el haz luminoso hacia: ");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 128));
        jLabel30.setText("Arriba para la retina superior");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 128));
        jLabel31.setText("Abajo para la retina inferior");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 128));
        jLabel32.setText("Al lado temporal para la retina temporal");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 128));
        jLabel33.setText("Al lado nasal para la retina nasal");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 128));
        jLabel34.setText("Para examinar el ojo izquierdo el oftalmoscopio se mantiene con la mano izquierda ante el ojo izquierdo");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 128));
        jLabel35.setText("del explorador y a la izquierda del paciente");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 128));
        jLabel36.setText("Repite todos los pasos anteriores");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 128));
        jLabel37.setText("Registra lo observado");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 183, 133));
        jLabel38.setText("Anormalidades: Fondo de ojo");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 128));
        jLabel39.setText("SI");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 128));
        jLabel40.setText("NO");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 128));
        jLabel41.setText("Papila: bordes no definidos; alteración en su coloración u excavación");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 128));
        jLabel42.setText("Alteraciones de la relación arteria/vena");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 128));
        jLabel43.setText("Hemorragias");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 128));
        jLabel44.setText("Exudados");

        btn_p1_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p1_SI.setText("jRadioButton1");

        btn_p1_No.setBackground(new java.awt.Color(255, 255, 255));
        btn_p1_No.setText("jRadioButton2");

        btn_p2_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p2_SI.setText("jRadioButton1");

        btn_p2_No.setBackground(new java.awt.Color(255, 255, 255));
        btn_p2_No.setText("jRadioButton2");

        btn_p3_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p3_SI.setText("jRadioButton1");

        btn_p3_No.setBackground(new java.awt.Color(255, 255, 255));
        btn_p3_No.setText("jRadioButton2");

        btn_p4_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p4_SI.setText("jRadioButton1");

        btn_p4_No.setBackground(new java.awt.Color(255, 255, 255));
        btn_p4_No.setText("jRadioButton2");

        btn_p5_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p5_SI.setText("jRadioButton1");

        btn_p5_No.setBackground(new java.awt.Color(255, 255, 255));
        btn_p5_No.setText("jRadioButton2");

        btn_p6_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p6_SI.setText("jRadioButton1");

        btn_p6_No.setBackground(new java.awt.Color(255, 255, 255));
        btn_p6_No.setText("jRadioButton2");

        btn_p7_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p7_SI.setText("jRadioButton1");

        btn_p7_No.setBackground(new java.awt.Color(255, 255, 255));
        btn_p7_No.setText("jRadioButton2");

        btn_p8_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p8_SI.setText("jRadioButton1");

        btn_p8_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p8_no.setText("jRadioButton2");

        btn_p9_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p9_SI.setText("jRadioButton1");

        btn_p9_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p9_no.setText("jRadioButton2");

        btn_p10_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p10_SI.setText("jRadioButton1");

        btn_p10_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p10_no.setText("jRadioButton2");

        btn_p11_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p11_SI.setText("jRadioButton1");

        btn_p11_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p11_no.setText("jRadioButton2");

        btn_p12_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p12_SI.setText("jRadioButton1");

        btn_p12_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p12_no.setText("jRadioButton2");

        btn_p13_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p13_SI.setText("jRadioButton1");

        btn_p13_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p13_no.setText("jRadioButton2");

        btn_p14_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p14_SI.setText("jRadioButton1");

        btn_p14_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p14_no.setText("jRadioButton2");

        btn_p15_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p15_SI.setText("jRadioButton1");

        btn_p15_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p15_no.setText("jRadioButton2");

        btn_p16_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p16_SI.setText("jRadioButton1");

        btn_p16_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p16_no.setText("jRadioButton2");

        btn_p17_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p17_SI.setText("jRadioButton1");

        btn_p17_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p17_no.setText("jRadioButton2");

        btn_p18_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p18_SI.setText("jRadioButton1");

        btn_p18_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p18_no.setText("jRadioButton2");

        btn_p19_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p19_SI.setText("jRadioButton1");

        btn_p19_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p19_no.setText("jRadioButton2");

        btn_p20_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p20_SI.setText("jRadioButton1");

        btn_p20_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p20_no.setText("jRadioButton2");

        btn_p21_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p21_SI.setText("jRadioButton1");

        btn_p21_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p21_no.setText("jRadioButton2");

        btn_p22_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p22_SI.setText("jRadioButton1");

        btn_p22_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p22_no.setText("jRadioButton2");

        btn_p23_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p23_SI.setText("jRadioButton1");

        btn_p23_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p23_no.setText("jRadioButton2");

        btn_p24_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p24_SI.setText("jRadioButton1");

        btn_p24_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p24_no.setText("jRadioButton2");

        btn_p25_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p25_SI.setText("jRadioButton1");

        btn_p25_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p25_no.setText("jRadioButton2");

        btn_p26_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p26_SI.setText("jRadioButton1");

        btn_p26_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p26_no.setText("jRadioButton2");

        btn_p27_SI.setBackground(new java.awt.Color(255, 255, 255));
        btn_p27_SI.setText("jRadioButton1");

        btn_p27_no.setBackground(new java.awt.Color(255, 255, 255));
        btn_p27_no.setText("jRadioButton2");

        btn_continuar.setText("Continuar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(btn_p15_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_p1_No, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel33)))
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn_p3_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(38, 38, 38)
                                                    .addComponent(btn_p3_No, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn_p2_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(38, 38, 38)
                                                    .addComponent(btn_p2_No, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btn_p1_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btn_p4_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_p4_No, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_p5_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_p5_No, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_p6_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_p6_No, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_p7_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_p7_No, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_p8_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_p8_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_p9_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_p9_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btn_p10_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(btn_p10_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_p12_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_p11_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_p13_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_p14_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_p15_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(38, 38, 38)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btn_p11_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn_p12_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btn_p14_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn_p13_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(btn_p18_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btn_p18_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(57, 57, 57))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_p19_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btn_p19_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_p20_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btn_p20_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_p21_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btn_p21_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57))))
                                    .addComponent(btn_p22_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_p23_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_p22_SI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_p23_SI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel39)
                                            .addGap(51, 51, 51)
                                            .addComponent(jLabel40))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_p26_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_p27_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(47, 47, 47)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_p26_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_p27_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_p25_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_p24_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_p24_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_p25_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_p17_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_p17_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(57, 57, 57)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_p16_no, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_p16_SI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(57, 57, 57))))))
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_continuar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btn_p1_SI)
                            .addComponent(btn_p1_No))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btn_p2_SI)
                            .addComponent(btn_p2_No))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_p3_SI)
                        .addComponent(btn_p3_No)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(btn_p4_SI)
                                    .addComponent(btn_p4_No))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_p5_SI)
                                .addComponent(btn_p5_No)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(btn_p6_SI)
                            .addComponent(btn_p6_No))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_p7_SI)
                        .addComponent(btn_p7_No)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btn_p8_SI)
                    .addComponent(btn_p8_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btn_p9_SI)
                    .addComponent(btn_p9_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btn_p10_SI)
                    .addComponent(btn_p10_no))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(btn_p11_SI)
                    .addComponent(btn_p11_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(btn_p12_SI)
                    .addComponent(btn_p12_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(btn_p13_SI)
                            .addComponent(btn_p13_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25))
                            .addComponent(btn_p14_no)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_p14_SI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_p15_SI)
                            .addComponent(btn_p15_no))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_p16_SI)
                        .addComponent(btn_p16_no)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(btn_p17_SI)
                    .addComponent(btn_p17_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(btn_p18_SI)
                    .addComponent(btn_p18_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(btn_p19_SI)
                    .addComponent(btn_p19_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(btn_p20_SI)
                    .addComponent(btn_p20_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(btn_p21_SI)
                    .addComponent(btn_p21_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(btn_p22_SI)
                    .addComponent(btn_p22_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(btn_p23_SI)
                    .addComponent(btn_p23_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_p24_SI)
                            .addComponent(btn_p24_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_p25_SI)
                            .addComponent(btn_p25_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_p26_SI)
                            .addComponent(btn_p26_no))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_p27_SI)
                            .addComponent(btn_p27_no))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btn_continuar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_continuar;
    public javax.swing.JRadioButton btn_p10_SI;
    public javax.swing.JRadioButton btn_p10_no;
    public javax.swing.JRadioButton btn_p11_SI;
    public javax.swing.JRadioButton btn_p11_no;
    public javax.swing.JRadioButton btn_p12_SI;
    public javax.swing.JRadioButton btn_p12_no;
    public javax.swing.JRadioButton btn_p13_SI;
    public javax.swing.JRadioButton btn_p13_no;
    public javax.swing.JRadioButton btn_p14_SI;
    public javax.swing.JRadioButton btn_p14_no;
    public javax.swing.JRadioButton btn_p15_SI;
    public javax.swing.JRadioButton btn_p15_no;
    public javax.swing.JRadioButton btn_p16_SI;
    public javax.swing.JRadioButton btn_p16_no;
    public javax.swing.JRadioButton btn_p17_SI;
    public javax.swing.JRadioButton btn_p17_no;
    public javax.swing.JRadioButton btn_p18_SI;
    public javax.swing.JRadioButton btn_p18_no;
    public javax.swing.JRadioButton btn_p19_SI;
    public javax.swing.JRadioButton btn_p19_no;
    public javax.swing.JRadioButton btn_p1_No;
    public javax.swing.JRadioButton btn_p1_SI;
    public javax.swing.JRadioButton btn_p20_SI;
    public javax.swing.JRadioButton btn_p20_no;
    public javax.swing.JRadioButton btn_p21_SI;
    public javax.swing.JRadioButton btn_p21_no;
    public javax.swing.JRadioButton btn_p22_SI;
    public javax.swing.JRadioButton btn_p22_no;
    public javax.swing.JRadioButton btn_p23_SI;
    public javax.swing.JRadioButton btn_p23_no;
    public javax.swing.JRadioButton btn_p24_SI;
    public javax.swing.JRadioButton btn_p24_no;
    public javax.swing.JRadioButton btn_p25_SI;
    public javax.swing.JRadioButton btn_p25_no;
    public javax.swing.JRadioButton btn_p26_SI;
    public javax.swing.JRadioButton btn_p26_no;
    public javax.swing.JRadioButton btn_p27_SI;
    public javax.swing.JRadioButton btn_p27_no;
    public javax.swing.JRadioButton btn_p2_No;
    public javax.swing.JRadioButton btn_p2_SI;
    public javax.swing.JRadioButton btn_p3_No;
    public javax.swing.JRadioButton btn_p3_SI;
    public javax.swing.JRadioButton btn_p4_No;
    public javax.swing.JRadioButton btn_p4_SI;
    public javax.swing.JRadioButton btn_p5_No;
    public javax.swing.JRadioButton btn_p5_SI;
    public javax.swing.JRadioButton btn_p6_No;
    public javax.swing.JRadioButton btn_p6_SI;
    public javax.swing.JRadioButton btn_p7_No;
    public javax.swing.JRadioButton btn_p7_SI;
    public javax.swing.JRadioButton btn_p8_SI;
    public javax.swing.JRadioButton btn_p8_no;
    public javax.swing.JRadioButton btn_p9_SI;
    public javax.swing.JRadioButton btn_p9_no;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup21;
    private javax.swing.ButtonGroup buttonGroup22;
    private javax.swing.ButtonGroup buttonGroup23;
    private javax.swing.ButtonGroup buttonGroup24;
    private javax.swing.ButtonGroup buttonGroup25;
    private javax.swing.ButtonGroup buttonGroup26;
    private javax.swing.ButtonGroup buttonGroup27;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    // End of variables declaration//GEN-END:variables
}
