/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brenda.libro.gui;

import javax.swing.JButton;

/**
 *
 * @author thefi
 */
public class PantallaTexto extends javax.swing.JPanel {

    /**
     * Creates new form PantallaTexto
     */
    public PantallaTexto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_anterior = new javax.swing.JButton();
        btn_sigPag = new javax.swing.JButton();
        btn_cuestionario = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        btn_anterior.setText("Anterior");
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_anterior);

        btn_sigPag.setText("Siguiente");
        jPanel1.add(btn_sigPag);

        btn_cuestionario.setText("Continuar");
        jPanel1.add(btn_cuestionario);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_cuestionario;
    private javax.swing.JButton btn_sigPag;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_anterior() {
        return btn_anterior;
    }

    public JButton getBtn_cuestionario() {
        return btn_cuestionario;
    }

    public JButton getBtn_sigPag() {
        return btn_sigPag;
    }


}
